<?php
declare(strict_types=1);

namespace zesk\Mail;

use zesk\Application;
use zesk\Module as BaseModule;

class Module extends BaseModule {
	public function initialize(): void {
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->application->registerFactory('Mail', $this->appMailFactory(...));
	}

	public function appMailFactory(Application $application, array $headers = [], string $body = '', array $options = []): Mail {
		return new Mail($application, $headers, $body, $options);
	}
}
