language: php
php:
- 5.5
- 5.6
- 7.0
- 7.1
services:
- mysql
before_install:
  - mysql -e "create database IF NOT EXISTS test_zesk;" -uroot
  - composer install
script: ./bin/zesk --zesk___Command_Test::travis --zesk___Module_Database::names::default=mysqli://root:@127.0.0.1/test_zesk test --debug --verbose --sandbox --no-config
