language: php
php:
- 5.4
- 5.5
- 5.6
- 7.0
services:
- mysql
before_install:
  - mysql -e "create database IF NOT EXISTS test_zesk;" -uroot
  - composer update
script: ./bin/zesk --Database::names::default=mysqli://root:@127.0.0.1/test_zesk test --debug --verbose --sandbox
