options:
  docker: true

definitions:
  caches:
    apt-lists: /var/lib/apt/lists
    apt-cache: /var/cache/apt
  docker:
    memory: 6144
  services:
    mariadb:
      memory: 1024
      image: mariadb:latest
      variables:
        MARIADB_ROOT_PASSWORD: hard-to-guess
        MYSQL_ROOT_PASSWORD: hard-to-guess

image: python:3
pipelines:
  branches:
    develop:
      - step:
          name: Build and test
          services:
            - mariadb
          artifacts:
            - .env
            - .build/
            - .release-notes.md
            - test-coverage/
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          deployment: staging
          size: 2x
          script:
            - export DATABASE_HOST=127.0.0.1
            - export DATABASE_ROOT_PASSWORD=hard-to-guess
            - bin/pipeline-setup.sh
    master:
      - step:
          name: Build and test
          services:
            - mariadb
          artifacts:
            - .env
            - .build/
            - .release-notes.md
            - test-coverage/
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          deployment: staging
          size: 2x
          script:
            - export DATABASE_HOST=127.0.0.1
            - export DATABASE_ROOT_PASSWORD=hard-to-guess
            - bin/pipeline-setup.sh
      - step:
          name: Deploy
          trigger: manual
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          script:
            - bin/pipeline-deploy.sh
