options:
  docker: true

definitions:
  caches:
    apt-lists: /var/lib/apt/lists
    apt-cache: /var/cache/apt

image: python:3
pipelines:
  branches:
    develop:
      - step:
          name: Build and test
          artifacts:
            - .env
            - .release-notes.md
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          deployment: staging
          script:
            - export DEPLOYMENT=staging
            - bin/pipeline-setup.sh "${DEPLOYMENT}" ${BUILD_TEST_FLAG} --host "${CONTAINER_HOST}" --commit "${BITBUCKET_COMMIT}"
    master:
      - step:
          name: Build and test
          artifacts:
            - .env
            - .release-notes.md
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          deployment: production
          script:
            - export DEPLOYMENT=production
            - bin/pipeline-setup.sh "${DEPLOYMENT}" ${BUILD_TEST_FLAG} --host "${CONTAINER_HOST}" --commit "${BITBUCKET_COMMIT}"
      - step:
          name: Deploy
          trigger: manual
          caches:
            - pip
            - docker
            - apt-lists
            - apt-cache
          script:
            - bin/pipeline-deploy.sh
