options:
  docker: true

definitions:
  caches:
    apt-lists: /var/lib/apt/lists
    apt-cache: /var/cache/apt
  services:
    mariadb:
      memory: 1024
      image: mariadb:latest
      variables:
        MARIADB_ROOT_PASSWORD: hard-to-guess
        MYSQL_ROOT_PASSWORD: hard-to-guess

image: atlassian/default-image:4
pipelines:
  branches:
    develop:
      - step:
          deployment: develop
          name: Build and test
          services:
            - mariadb
          artifacts:
            - .env
            - .build/
            - .release-notes.md
            - test-coverage/
            - test.log
            - .memory_get_usage
            - memory-logs.txt
          caches:
            - docker
            - apt-lists
            - apt-cache
          script:
            - while true; do date && echo -n "Memory usage in megabytes:" && echo $(($(cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes | awk '{print $1}')/1048576)) && echo "" && sleep 30; done >> memory-logs.txt &
            - export CONTAINER_DATABASE_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
            - bin/pipeline-setup.sh --develop --testsuite core
    production:
      - step:
          deployment: production
          name: Build and test
          services:
            - mariadb
          artifacts:
            - .env
            - .build/
            - .release-notes.md
            - test-coverage/
            - test.log
            - .memory_get_usage
            - memory-logs.txt
          caches:
            - docker
            - apt-lists
            - apt-cache
          size: 2x
          script:
            - while true; do date && echo -n "Memory usage in megabytes:" && echo $(($(cat /sys/fs/cgroup/memory/memory.memsw.usage_in_bytes | awk '{print $1}')/1048576)) && echo "" && sleep 30; done >> memory-logs.txt &
            - export CONTAINER_DATABASE_HOST=$BITBUCKET_DOCKER_HOST_INTERNAL
            - bin/pipeline-setup.sh --testsuite core
      - step:
          name: Deploy
          trigger: manual
          size: 2x
          artifacts:
            - .env
          script:
            - bin/pipeline-release.sh
    deploy:
      - step:
          deployment: deploy
          name: Deploy Testing
          size: 2x
          script:
            - bin/pipeline-release.sh
