version: "3"

services:
  php:
    env_file: docker/etc/env.sh
    environment:
      BUILD_CODE: php
    build:
      context: ./
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - ./:/zesk
    ports:
      - "4026:4026"
  mariadb:
    env_file: docker/etc/env.sh
    environment:
      BUILD_CODE: mariadb
      MARIADB_ROOT_PASSWORD: hard-to-guess
    build:
      context: ./
      dockerfile: ./docker/mariadb.Dockerfile
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD-SHELL", "/db-health.sh"]
      interval: 2s
      timeout: 2s
      retries: 10
volumes:
  database_data:
    driver: local
