#! /bin/sh

canonCMD=${1:-dk_canonicalize -c}

myExit=0
rm -f *.txt

for testFile in email.*
do
  testNumber=`echo $testFile | cut -f2 -d.`

  for canon in simple nofws
  do
    printf "test canonicalize %s %s " $testNumber $canon
    ${canonCMD} ${canon} <$testFile >${canon}.actual.${testNumber}.txt
    if [ $? -ne 0 ]; then
	echo command failed.
	myExit=1
	next
    fi
    cmp -s ${canon}.expected.${testNumber} ${canon}.actual.${testNumber}.txt
    if [ $? -ne 0 ]; then
	echo failed
	myExit=1
    else
	echo Ok
    fi
  done
done

exit $myExit
