<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/modules/import_log/classes/import/log/webserver/apache.inc $
 * @package ruler
 * @subpackage import
 * @author kent
 * @copyright Copyright &copy; 2009, Market Ruler, LLC
 * Created on Wed Feb 24 13:48:13 EST 2010 13:48:13
 */
namespace zesk;

class Import_Log_WebServer_Apache extends Import_Log_WebServer {
	function read_line() {
		// TODO
	}
}
