<?php
/**
 * @version $URL: https://code.marketacumen.com/zesk/trunk/classes/application.inc $
 * @package zesk
 * @subpackage objects
 * @author $Author: kent $
 * @copyright Copyright &copy; 2011, Market Acumen, Inc.
 * Created on Mon,Aug 1, 11 at 5:08 PM
 */

/**
 * Override, or subclass this class in your application to get core functionality
 *
 * @author kent
 */
class Application extends zesk\Application {

}
