<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/arr.inc $
 * @package zesk
 * @subpackage system
 * @author kent
 * @copyright Copyright &copy; 2009, Market Acumen, Inc.
 *            Created on Wed Feb 03 01:41:11 EST 2010 01:41:11
 */
zesk()->deprecated();
/**
 * Array tools for pretty much anything you can think of for arrays.
 * @deprecated 2016-09
 * @author kent
 */
class arr extends zesk\arr {}
