<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/server.inc $
 * @package zesk
 * @subpackage objects
 * @author Kent Davidson <kent@marketacumen.com>
 * @copyright Copyright &copy; 2005, Market Acumen, Inc.
 */

/**
 * Server
 *
 * Represents a physical machine. Override this in your own tree to extend
 * columns and functionality. Override Class_Server to add columns or modify defaults.
 *
 * @see Class_Server
 * @see Class_Zesk_Server
 * @see Zesk_Server
 */
class Server extends Zesk_Server {}
