<?php
/**
 * Integration with operating system. Host name, process ID, system services, load averages, volume info.
 *
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/system.inc $
 * @package zesk
 * @subpackage default
 * @author Kent Davidson <kent@marketacumen.com>
 * @copyright Copyright &copy; 2006, Market Acumen, Inc.
 */

zesk()->deprecated();
/**
 *
 * @author kent
 *        
 */
class system extends zesk\System {}
