<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/text.inc $
 * @package zesk
 * @subpackage tools
 * @author Kent Davidson <kent@marketacumen.com>
 * @copyright Copyright &copy; 2008, Market Acumen, Inc.
 * @desc Text Manipulation
 */
zesk()->deprecated();

/**
 * The text class deals with manipulation of text, specifically for output to a console or fixed-width font output, or email.
 *
 * @author kent
 * @deprecated 2016-08
 */
class Text extends zesk\Text {}

