<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/time.inc $
 * @package zesk
 * @subpackage system
 * @author Kent Davidson <kent@marketacumen.com>
 * @copyright Copyright &copy; 2015, Market Acumen, Inc.
 */
zesk()->deprecated();
/**
 * @author Kent M. Davidson <kent@marketacumen.com>
 * @package zesk
 * @subpackage model
 * @desc Time of day
 */
class Time extends zesk\Time {}
