<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/classes/url.inc $
 * @package zesk
 * @subpackage system
 * @author kent
 * @copyright Copyright &copy; 2014, Market Acumen, Inc.
 */
zesk()->deprecated();
/**
 * URL formatting and manipulation.
 *
 * Supports retrieval of current request information in URL::current* calls.
 * @deprecated 2016-09
 * @author kent
 */
class url extends zesk\URL {}

