<?php
$index_file = $this->index_file;

$directory_index = $this->get("directory_index", "index.php");
$directory_index_pq = preg_quote($directory_index);

echo "#\n";
echo "# Automatically Generated by Module_Apache - do not edit\n";
echo "#\n";
echo "<IfModule mod_rewrite.c>\n";
echo "RewriteEngine On\n";
echo "RewriteBase /\n";
echo "RewriteCond %{REQUEST_FILENAME} !-f\n";
echo "RewriteCond %{REQUEST_FILENAME} !-d\n";
echo "RewriteRule . " . $directory_index . " [L]\n";
echo "\n";
echo "</IfModule>\n";
echo "<IfModule mod_dir.c>\n";
echo "DirectoryIndex $directory_index /$directory_index\n";
echo "</IfModule>\n";

