<?php
class Module_Feed extends Module {

/**
 * List of associated classes
 *
 * @var array
 */
	/*
	 protected $classes = array();
	 */

/**
 * Override in subclasses - called upon Application::classes
 */
	/*
	 public function classes() {
	 return $this->classes;
	 }
	 */
	
	/*
	 public function initialize() {
	 parent::initialize();
	 }
	 */
	
	/*
	 protected function hook_foot(Request $request, Response_HTML $response, Template $template) {
	 
	 }
	 */
	
	/*
	 protected function hook_head(Request $request, Response_HTML $response, Template $template) {
	 
	 }
	 */
	
	/*
	 public function hook_routes(Router $router) {
	 
	 }
	 */
}
