CREATE TABLE `{table}` (
	`id` 				integer unsigned NOT NULL AUTO_INCREMENT,
	`code`	 			varchar(32) NOT NULL DEFAULT '',
	`description`		text,
	`message`			text,
	`billed` 			timestamp NOT NULL DEFAULT 0,
	`due`	 			timestamp NOT NULL DEFAULT 0,
	`created` 			timestamp NOT NULL DEFAULT 0,
	`modified` 			timestamp NOT NULL DEFAULT 0,
	`notified` 			timestamp NOT NULL DEFAULT 0,
	`computed` 			timestamp NOT NULL DEFAULT 0,
	`account` 			integer unsigned NOT NULL,
	`payment_invoice`	integer unsigned NULL,
	`currency`			integer unsigned NOT NULL,
	`credits`			decimal(12,2) DEFAULT NULL,
	`debits`			decimal(12,2) DEFAULT NULL,
	`subtotal`			decimal(12,2) DEFAULT NULL,
	`tax`				decimal(12,2) DEFAULT NULL,
	`total`				decimal(12,2) DEFAULT NULL,
	`total_due`			decimal(12,2) DEFAULT NULL,
	`payment_total`		decimal(12,2) DEFAULT NULL,
	`reconciled` 		tinyint unsigned NOT NULL DEFAULT 0,
	`paid`	 			tinyint unsigned NOT NULL DEFAULT 0,,
	PRIMARY KEY (`id`),
	INDEX `code` (`code`),
	INDEX `account` (`account`)
) ENGINE=InnoDB;
