<?php
declare(strict_types=1);

namespace zesk;

class CTest extends Controller {
	public function initialize(): void {
		parent::initialize(); // TODO: Change the autogenerated stub
		$this->application->optionAppend(__CLASS__, 'init', );
	}

	public function action_index(string $a = '', string $b = '') {
		$this->application->optionAppend(__CLASS__, [$a, $b]);
		return "$a|$b";
	}

	public function action_array(string $a, string $b, Request $request) {
		$this->application->optionAppend(__CLASS__, [$a, $b]);
		return ['first' => $a, 'second' => $b, 'request' => $request];
	}

	public static function getOption(Application $app): array {
		return $app->optionArray(__CLASS__);
	}
}

class Controller_Test extends UnitTest {
	/**
	 *
	 */
	public function test_Controller(): void {
		$app = $this->application;

		$app->setOption('cache_router', false);
		$router = $app->router();

		$router->addRoute('index', ['controller' => Ctest::class, 'arguments' => [0, 1], 'action' => 'index', 'default' => true]);
		$router->addRoute('array(/{what}(/{verb}))', [
			'controller' => Ctest::class, 'arguments' => [1, 2, '{Request}'], 'action' => 'array',
		]);

		$request = Request::factory($app, 'http://localhost/index');

		$route = $router->match($request);
		$this->assertInstanceOf(Route_Controller::class, $route);

		$response = $route->execute();
		$this->assertInstanceOf(Response::class, $response);

		$this->asertEquals(['init', ['index', '']], CTest::getOption($this->application));
	}
}
