<?php
declare(strict_types=1);

namespace zesk;

echo '<?';
?>php

declare(strict_types=1);

namespace <?php echo $this->get('namespace', 'zesk'); ?>;
/*
 * This file was autogenerated on <?php echo Timestamp::now()->format(); ?>
 */
class <?php echo $this->get('class'); ?> {
	public function schema(): array {
		return <?php Text::indent(PHP::dump($this->get('schema')), 3); ?>;
	}
}
