<?php
/**
 * @version $Id: file.inc 2079 2014-02-03 15:06:29Z kent $
 * @package zesk
 * @subpackage content
 * @author Kent Davidson <kent@marketacumen.com>
 * @copyright Copyright &copy; 2012, Market Acumen, Inc.
 */

/**
 * Placeholder to override with custom code
 *
 * @author kent
 * @see Class_Content_File
 * @property string $Original
 * @property string $MIMEType
 * @property Content_Data $Content_Data
 * @property string $Description
 * @property User $User
 * @property Timestamp $Created
 * @property Timestamp $Modified
 */
class Content_File extends Zesk_Content_File {}
