<?php
class Module_QuickList extends Module_JSLib /* implements Module_Interface_Head, Module_Interface_Foot, Module_Interface_Routes */
{
	protected $javascript_paths = array(
		"/share/quicklist/js/jquery.quicklist.js" => array(
			"share" => true
		)
	);
/**
 * List of associated classes
 *
 * @var array
 */
	/*
	 protected $classes = array();
	 */

/**
 * Override in subclasses - called upon Application::classes
 */
	/*
	 public function classes() {
	 return $this->classes;
	 }
	 */
	
	/*
	 public function initialize() {
	 parent::initialize();
	 }
	 */
	
	/*
	 protected function hook_foot(Request $request, Response_HTML $response, Template $template) {
	 
	 }
	 */
	
	/*
	 protected function hook_head(Request $request, Response_HTML $response, Template $template) {
	 
	 }
	 */
	
	/*
	 public function hook_routes(Router $router) {
	 
	 }
	 */
}
