<?php
/**
 *
 * @version $URL: https://code.marketacumen.com/zesk/trunk/classes/exception/authentication.inc $
 * @package zesk
 * @subpackage system
 * @author $Author: kent $
 * @copyright Copyright &copy; 2011, Market Acumen, Inc.
 */

/**
 * Throw when the user does not authenticate, authentication fails, or access issues
 * 
 * @author kent
 */
class Exception_Authentication extends Zesk_Exception {
}
