<?php
/**
 * $URL: https://code.marketacumen.com/zesk/trunk/etc/language/fr.inc $
 * @package zesk
 * @subpackage locale
 * @author kent
 * @copyright Copyright &copy; 2008, Market Acumen, Inc.
 * Created on Thu Jan 22 12:10:40 EST 2009 12:10:40
 */

$tt = array();

$tt['Date:=format_long'] = 'le {WWWW} {DDD} {MMMM} {YYYY}';

// Generic terms
$tt['and'] = "et";
$tt['name'] = "nom";
$tt['special'] = "sp&eacute;cial";
$tt['current'] = "s&eacute;lectionn&eacute;";
$tt['organic'] = 'naturel';
$tt['active'] = 'actif';
$tt['inactive'] = 'inactif';
$tt['search'] = 'recherche';
$tt['loading'] = 'chargement';
$tt['product'] = 'produit';
$tt['activated'] = 'activ&eacute;';
$tt['deactivated'] = 'd&eacute;sactiv&eacute;s';
$tt['deactivate'] = 'd&eacute;sactiv&eacute;r';
$tt['select'] = 's&eacute;lectionner';
$tt['actions'] = 'actions';
$tt['access'] = 'acc&egrave;s';
$tt['new'] = 'cr&eacute;er';
$tt['install'] = "installer";
$tt['news'] = "nouvelles";
$tt['Browse'] = 'Brouter';
$tt['edit'] = 'modifier';
$tt['logout'] = "sortie";
$tt['account'] = 'compte';
$tt['cancel'] = 'annuler';
$tt['email address'] = 'adresse e-mail';
$tt['password'] = 'mot de passe';
$tt['user name'] = 'nom d\'utilisateur';
$tt['first name'] = 'pr&eacute;nom';
$tt['last name'] = 'nom';
$tt['title'] = 'titre';
$tt['phone'] = 't&eacute;l&eacute;phone';
$tt['home page'] = 'Page d\'accueil';
$tt['again for confirmation'] = 'encore pour confirmation';
$tt['user'] = 'utilisateur';
$tt['preference'] = 'pr&eacute;f&eacute;rence';
$tt['preferences'] = 'pr&eacute;f&eacute;rences';

// Dates and times
$tt['today'] = 'aujourd\'hui';
$tt['yesterday'] = 'hier';
$tt['tomorrow'] = 'demain';
$tt['this week'] = 'cette semaine';
$tt['last 7 days'] = 'Depuis 7 jours';
$tt['last week'] = 'le semaine derni&egrave;re';
$tt['last quarter'] = 'le quarti&egrave;me derni&egrave;re';
$tt['this quarter'] = 'ce quarti&egrave;me';
$tt['this month'] = 'ce mois';
$tt['last month'] = 'le mois derni&egrave;re';
$tt['last 180 days'] = 'depuis 180 jours';
$tt['this year'] = 'cette ann&eacute;e';
$tt['last year'] = 'l\'ann&eacute;e derni&egrave;re';

$tt['Locale::now_string:=in {0}'] = "en {0}";
$tt['Locale::now_string:={0} ago'] = "il y a {0}";

$tt['seconds'] = "secondes";
$tt['second'] = "seconde";
$tt['minutes'] = "minutes";
$tt['minute'] = "minute";
$tt['hours'] = "heures";
$tt['hour'] = "heure";
$tt['day'] = "jour";
$tt['days'] = "jours";
$tt['weeks'] = "semaines";
$tt['week'] = "semaine";
$tt['months'] = "mois";
$tt['month'] = "mois";
$tt['year'] = "an";
$tt['years'] = "ans";

$tt['Sunday'] = 'dimanche';
$tt['Monday'] = 'lundi';
$tt['Tuesday'] = 'mardi';
$tt['Wednesday'] = 'mercredi';
$tt['Thursday'] = 'jeudi';
$tt['Friday'] = 'vendredi';
$tt['Saturday'] = 'samedi';

$tt['January'] = 'janvier';
$tt['February'] = 'f&eacute;brier';
$tt['March'] = 'mars';
$tt['April'] = 'avril';
$tt['May'] = 'mai';
$tt['June'] = 'juin';
$tt['July'] = 'juillet';
$tt['August'] = 'ao&uuml;t';
$tt['September'] = 'septembre';
$tt['October'] = 'octobre';
$tt['November'] = 'novembre';
$tt['December'] = 'd&eacute;cembre';

$tt['Locale::plural_word:=no {0}'] = 'Pas de {0}';
$tt['Locale::plural_word:=1 {0}'] = '1 {0}';

$tt['Control_Pager:=Showing {0} - {1} of {2}'] = "Afficher {0} &aacute; {1} de {2}";
$tt['Control_Pager:=Show'] = "Afficher";

return $tt;
